version: '3.8'
services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: db_postgres
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql
volumes:
  postgres_data:
    driver: local
